title:            Adventures in Analytics and Visualization
description:      Vivek Patil's website and blog for analytics and visualization
disqus_shortname: analyticsandvisualization
#url:              http://localhost:4000
url:              http://patilv.github.io
# Owner/author information

owner:
  name:           Vivek Patil
  avatar:         Vivekwebsite.jpg
  bio:            ""
  email:          patilv@gmail.com
  
# Social networking links used in footer. Update and remove as you like.
  twitter:        vivekhpatil
  facebook:       
  github:         patilv
  stackexchange:  
  linkedin:       vpatil
  instagram:        
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/0/105720047530833545102/posts

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-44143720-2
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: R Resources
    url: /r-resources
  - title: Public Datasets
    url: /public-datasets
  - title: Besides Data Analysis
    url: /besidesDA
    #external: true
  

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Seattle
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Number of posts in most recent posts
paginate: 1

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
